spring.datasource.url=jdbc:postgresql://dpg-d8evi1mq1p3s73dcqjdg-a.oregon-postgres.render.com:5432/agenda_escolar_52bp

spring.datasource.username=agenda_user

spring.datasource.password=EMaCMWrRHuU7rgkdbNWCAiNGmwyh4DLu

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect