spring.datasource.url=jdbc:mysql://localhost:3306/agenda_escolar
spring.datasource.username=root
spring.datasource.password=052070

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.address=0.0.0.0
